---
published: true
author: Kent Chiu
layout: post
title: "RxSwift 101"
date: 2015-12-23 14:30
tags: 
- ios
- rfp
---

## Table of contents
{:.no_toc}

* Will be replaced with the ToC, excluding the "Contents" header
{:toc}


----------------------------------------------------------------



- 元件用driver
- 錯誤訊息用just
- 在class 用一個 `DisposeBag`蒐集所有disposiables
- 在unit test裡的observable 不會被觸發，但如果程式用debugging mode的step run又會更常被觸發，可能是thread引起的問題，目前最簡單的解法是在unit test裡引都RxBlocking
- Sequence 在 subscribe 被調用後才會開始產生


#### Multiple output

雖然 Swfit 2 有提供 Exception Handling，但是這個在 Function Programming 裡並不好使， 因為它是透過中斷整個處理流程的方式處理 exception，但在 Function Programming 應該是要 一個操作串接著一個操作一直往下做的，所以，在Function Programming的異常處理通常是透過下面的方式

function programming 的基本流程是 `IPO` (Input -> Process -> Output), 如果需要多種輸出的結果，可以用以下這個 ([Monad](http://adit.io/posts/2013-04-17-functors,_applicatives,_and_monads_in_pictures.html)), 輸出可以有兩種(或多種)

```
type Result =
    | Success
    | Failure
```    

- Either<A, B> type 
- Result<Success,Failure>
- Optional<Some, None>

經過這樣子的處理後，對於 exception flow的處理就變得很直觀，像這樣

``` type LogingResult = 
    | User Not Exist  
    | Password not confirmed
    | Password not match
    | Account is disabled
    | ...
    | Login Success
```

一般如果是用 imperative language (指令式語法)，就是一堆 `if / else`, 或 `try / catch`的流程處理, 而在 functional language 就是一個function串著一個function的方式一直寫下來(Pipeline)，最後進入 happy path(成功)


關於這樣的寫法，強列建議仔細看過[Railway oriented programming](http://fsharpforfunandprofit.com/posts/recipe-part2/)的文章及影片

